// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gspepwxrelzbppfezwjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcGVwd3hyZWx6YnBwZmV6d2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MDU3NzYsImV4cCI6MjA4NzM4MTc3Nn0.51Eea5fwcEbgJjKX4l2pVUw1s3kk3FTynRrFlK-krm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});